coverage:
  status:
    project:
      default: off
      unit:
        flags: unit
      nightly:
        flags: nightly
      newnightly:
        flags: newnightly

flags:
  unit:
    joined: true
  nightly:
    joined: false
  newnightly:
    joined: false
